name: Next yaml file

on: push

jobs:

  under_first_1:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name: under first
        run: cat README.md
