name: my first workflow

on: push

jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
      - name: My first step
        run: echo "This is the job"

      - name: "Print the environment variables"
        run: printenv