name: my first workflow

on: push

jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
      - name: checkout to repo
        uses: actions/checkout@v4

      - name: My first step
        run: |
           set -x
           echo "This is the job"
           ls -ltra
           cat README.md
           printenv

      - name: "use cowsay"
        run: cowsay -f dragon " Running a new cosay command .. This is dragon!!!!!!" > dragon.txt