name: my first workflow

on: push

jobs:
   build_job1:
     runs-on: ubuntu-latest
     steps:
      - name: checkout to repo
        uses: actions/checkout@v4
      
      - name: build the artifact
        run: |
           sudo apt-get install cowsay -y
           cowsay -f dragon " Running a new cosay command .. This is dragon!!!!!!" >> dragon.txt
           cat dragon.txt
           ls -ltra
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-artifact
          path: dragon.txt
    
   test_job2: 
      runs-on: ubuntu-latest
      needs: build_job1
      steps:
        - name: checkout to repo
          uses: actions/checkout@v4

        - name: download artifact
          uses: actions/download-artifact@v4
          with:
               name: dragon-artifact

        - name: test the file generated
          run: |
             ls -ltra
             grep -i dragon dragon.txt

   deploy_job3:
       runs-on: ubuntu-latest
       needs: build_job1
       steps:
         - name: deploy 
           run: echo " This is the deploy"

         - name: download artifact
           uses: actions/download-artifact@v4
           with:
                name: dragon-artifact
 
         - name: deploy the file generated
           run: cat dragon.txt


