name: To learn variable
on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
          - name: check the variable
            env:
              DOCKER: Test
              USER: arsha
            run: echo  docker build -t $DOCKER:$USER